In [18]:
import numpy as np

docs = [
    'hellow this is me',
    'how are you?',
    "don't ever touch me",
    "speak less, work more",
    "stay hydrated and stay cool",
    "don't be in hurry",
    "parmish verma: tabaah",
    "paindi aa pher dhakk champion",
    "aston martin db11 is my dream car",
    "sandwich"
]

In [19]:
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token='<nothing>')

In [20]:
tokenizer.fit_on_texts(docs)

In [21]:
tokenizer.word_index

{'<nothing>': 1,
 'is': 2,
 'me': 3,
 "don't": 4,
 'stay': 5,
 'hellow': 6,
 'this': 7,
 'how': 8,
 'are': 9,
 'you': 10,
 'ever': 11,
 'touch': 12,
 'speak': 13,
 'less': 14,
 'work': 15,
 'more': 16,
 'hydrated': 17,
 'and': 18,
 'cool': 19,
 'be': 20,
 'in': 21,
 'hurry': 22,
 'parmish': 23,
 'verma': 24,
 'tabaah': 25,
 'paindi': 26,
 'aa': 27,
 'pher': 28,
 'dhakk': 29,
 'champion': 30,
 'aston': 31,
 'martin': 32,
 'db11': 33,
 'my': 34,
 'dream': 35,
 'car': 36,
 'sandwich': 37}

In [22]:
tokenizer.word_counts

OrderedDict([('hellow', 1),
             ('this', 1),
             ('is', 2),
             ('me', 2),
             ('how', 1),
             ('are', 1),
             ('you', 1),
             ("don't", 2),
             ('ever', 1),
             ('touch', 1),
             ('speak', 1),
             ('less', 1),
             ('work', 1),
             ('more', 1),
             ('stay', 2),
             ('hydrated', 1),
             ('and', 1),
             ('cool', 1),
             ('be', 1),
             ('in', 1),
             ('hurry', 1),
             ('parmish', 1),
             ('verma', 1),
             ('tabaah', 1),
             ('paindi', 1),
             ('aa', 1),
             ('pher', 1),
             ('dhakk', 1),
             ('champion', 1),
             ('aston', 1),
             ('martin', 1),
             ('db11', 1),
             ('my', 1),
             ('dream', 1),
             ('car', 1),
             ('sandwich', 1)])

In [23]:
tokenizer.document_count

10

In [24]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[6, 7, 2, 3],
 [8, 9, 10],
 [4, 11, 12, 3],
 [13, 14, 15, 16],
 [5, 17, 18, 5, 19],
 [4, 20, 21, 22],
 [23, 24, 25],
 [26, 27, 28, 29, 30],
 [31, 32, 33, 2, 34, 35, 36],
 [37]]

In [25]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences, padding='post')
sequences

array([[ 6,  7,  2,  3,  0,  0,  0],
       [ 8,  9, 10,  0,  0,  0,  0],
       [ 4, 11, 12,  3,  0,  0,  0],
       [13, 14, 15, 16,  0,  0,  0],
       [ 5, 17, 18,  5, 19,  0,  0],
       [ 4, 20, 21, 22,  0,  0,  0],
       [23, 24, 25,  0,  0,  0,  0],
       [26, 27, 28, 29, 30,  0,  0],
       [31, 32, 33,  2, 34, 35, 36],
       [37,  0,  0,  0,  0,  0,  0]], dtype=int32)

# **Integer Encoding**

In [26]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense, SimpleRNN, Embedding, Flatten

In [27]:
(x_train, y_train), (x_test, y_test) = imdb.load_data()
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((25000,), (25000,), (25000,), (25000,))

In [32]:
x_train = pad_sequences(x_train, padding='post', maxlen=50) # maxlen=50
x_test = pad_sequences(x_test, padding='post', maxlen=50) # maxlen=50

In [33]:
x_train.shape

(25000, 50)

In [37]:
model = Sequential()

model.add(SimpleRNN(32, input_shape=(200,1), return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ simple_rnn_3 (SimpleRNN)             │ (None, 32)                  │           1,088 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,121 (4.38 KB)

 Trainable params: 1,121 (4.38 KB)

 Non-trainable params: 0 (0.00 B)

In [35]:
len(x_train[1])

50

In [36]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5, validation_data=(x_test, y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 12s 13ms/step - accuracy: 0.4978 - loss: 0.6934 - val_accuracy: 0.5000 - val_loss: 0.6931
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 21s 14ms/step - accuracy: 0.4983 - loss: 0.6932 - val_accuracy: 0.5000 - val_loss: 0.6931
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 13s 17ms/step - accuracy: 0.4989 - loss: 0.6932 - val_accuracy: 0.5000 - val_loss: 0.6931
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 18s 14ms/step - accuracy: 0.4891 - loss: 0.6932 - val_accuracy: 0.5000 - val_loss: 0.6931
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 10s 13ms/step - accuracy: 0.5018 - loss: 0.6932 - val_accuracy: 0.5000 - val_loss: 0.6932


# **Embeddings**

In [38]:
docs = [
    'hellow this is me',
    'how are you?',
    "don't ever touch me",
    "speak less, work more",
    "stay hydrated and stay cool",
    "don't be in hurry",
    "parmish verma: tabaah",
    "paindi aa pher dhakk champion",
    "aston martin db11 is my dream car",
    "sandwich"
]

In [41]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [42]:
tokenizer.fit_on_texts(docs)

In [43]:
len(tokenizer.word_index)

36

In [44]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[5, 6, 1, 2],
 [7, 8, 9],
 [3, 10, 11, 2],
 [12, 13, 14, 15],
 [4, 16, 17, 4, 18],
 [3, 19, 20, 21],
 [22, 23, 24],
 [25, 26, 27, 28, 29],
 [30, 31, 32, 1, 33, 34, 35],
 [36]]

In [45]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences, padding='post')
sequences

array([[ 5,  6,  1,  2,  0,  0,  0],
       [ 7,  8,  9,  0,  0,  0,  0],
       [ 3, 10, 11,  2,  0,  0,  0],
       [12, 13, 14, 15,  0,  0,  0],
       [ 4, 16, 17,  4, 18,  0,  0],
       [ 3, 19, 20, 21,  0,  0,  0],
       [22, 23, 24,  0,  0,  0,  0],
       [25, 26, 27, 28, 29,  0,  0],
       [30, 31, 32,  1, 33, 34, 35],
       [36,  0,  0,  0,  0,  0,  0]], dtype=int32)

In [46]:
model = Sequential()

model.add(Embedding(17, output_dim=2, input_length=5))

model.summary()

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [48]:
model.compile(optimizer='adam', metrics=['accuracy'])

In [49]:
pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 177ms/step
[[[ 0.00316662  0.0076075 ]
  [ 0.04534883  0.04256698]
  [-0.00394385 -0.0120585 ]
  [-0.04723431 -0.01331706]
  [ 0.04866127  0.04967084]
  [ 0.04866127  0.04967084]
  [ 0.04866127  0.04967084]]

 [[ 0.03707358  0.03347827]
  [ 0.04896364 -0.04847375]
  [ 0.00531838  0.02060629]
  [ 0.04866127  0.04967084]
  [ 0.04866127  0.04967084]
  [ 0.04866127  0.04967084]
  [ 0.04866127  0.04967084]]

 [[-0.03289308  0.02515843]
  [ 0.00974691  0.04326539]
  [-0.03126341 -0.0009323 ]
  [-0.04723431 -0.01331706]
  [ 0.04866127  0.04967084]
  [ 0.04866127  0.04967084]
  [ 0.04866127  0.04967084]]

 [[-0.0181819   0.02540166]
  [-0.04513381 -0.0284686 ]
  [-0.03241407 -0.03956777]
  [-0.01864986  0.01378349]
  [ 0.04866127  0.04967084]
  [ 0.04866127  0.04967084]
  [ 0.04866127  0.04967084]]

 [[-0.02848946 -0.04106312]
  [-0.00880032  0.01884219]
  [-0.00880032  0.01884219]
  [-0.02848946 -0.04106312]
  [-0.00880032  0.01884219]
  [ 0.04866127  0.04967084]
 

In [62]:
from keras.datasets import imdb
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense, SimpleRNN, Embedding, Flatten

In [63]:
(x_train, y_train), (x_test, y_test) = imdb.load_data()
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((25000,), (25000,), (25000,), (25000,))

In [64]:
x_train = pad_sequences(x_train, padding='post', maxlen=50) # maxlen=50
x_test = pad_sequences(x_test, padding='post', maxlen=50) # maxlen=50

In [65]:
x_train.shape

(25000, 50)

In [66]:
model = Sequential()

model.add(Embedding(10000, 2))
model.add(SimpleRNN(32, return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.summary()

Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn_6 (SimpleRNN)             │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_6 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [67]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

hsitory = model.fit(x_train, y_train, epochs=5, validation_data=(x_test, y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 13s 13ms/step - accuracy: 0.5522 - loss: 0.6701 - val_accuracy: 0.7866 - val_loss: 0.4555
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 17s 10ms/step - accuracy: 0.8155 - loss: 0.4186 - val_accuracy: 0.7956 - val_loss: 0.4503
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.8518 - loss: 0.3615 - val_accuracy: 0.7863 - val_loss: 0.4691
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.8486 - loss: 0.3601 - val_accuracy: 0.7884 - val_loss: 0.4877
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.8652 - loss: 0.3406 - val_accuracy: 0.7771 - val_loss: 0.5255
